services:
  - type: web
    name: artist-submission
    env: php
    repo: https://github.com/alexdame/artist-submission
    branch: master
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:GENERATE_YOURS
